# Generated by Django 4.2.7 on 2023-12-04 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='GP',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='referrals.doctor'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='referrals.doctor'),
        ),
    ]
