# Generated by Django 4.2.7 on 2023-12-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_alter_person_gp_alter_referral_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='portrait_img',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
