# Generated by Django 4.2.7 on 2023-12-29 21:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0004_alter_doctor_portrait_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='person',
            new_name='patient',
        ),
    ]
